/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignLeiterRequest } from '../../models/assign-leiter-request';
import { LeiterDto } from '../../models/leiter-dto';

export interface AssignLeiter$Params {
  slug: string;
      body: AssignLeiterRequest
}

export function assignLeiter(http: HttpClient, rootUrl: string, params: AssignLeiter$Params, context?: HttpContext): Observable<StrictHttpResponse<LeiterDto>> {
  const rb = new RequestBuilder(rootUrl, assignLeiter.PATH, 'post');
  if (params) {
    rb.path('slug', params.slug, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeiterDto>;
    })
  );
}

assignLeiter.PATH = '/stufen/{slug}/leiter';
