/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UebungDto } from '../../models/uebung-dto';

export interface ListUebungen$Params {
  slug: string;
}

export function listUebungen(http: HttpClient, rootUrl: string, params: ListUebungen$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UebungDto>>> {
  const rb = new RequestBuilder(rootUrl, listUebungen.PATH, 'get');
  if (params) {
    rb.path('slug', params.slug, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UebungDto>>;
    })
  );
}

listUebungen.PATH = '/stufen/{slug}/uebungen';
