/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Update$Params as Update$Params } from './fn/uebungen/update';
export { update as update } from './fn/uebungen/update';
export type { Delete$Params as Delete$Params } from './fn/uebungen/delete';
export { delete$ as delete$ } from './fn/uebungen/delete';
export type { Create1$Params as Create1$Params } from './fn/uebungen/create-1';
export { create1 as create1 } from './fn/uebungen/create-1';
export type { SetStatus$Params as SetStatus$Params } from './fn/uebungen/set-status';
export { setStatus as setStatus } from './fn/uebungen/set-status';
export type { GetBySlug$Params as GetBySlug$Params } from './fn/stufen/get-by-slug';
export { getBySlug as getBySlug } from './fn/stufen/get-by-slug';
export type { Update1$Params as Update1$Params } from './fn/stufen/update-1';
export { update1 as update1 } from './fn/stufen/update-1';
export type { ListAll$Params as ListAll$Params } from './fn/stufen/list-all';
export { listAll as listAll } from './fn/stufen/list-all';
export type { Create$Params as Create$Params } from './fn/stufen/create';
export { create as create } from './fn/stufen/create';
export type { ListUebungen$Params as ListUebungen$Params } from './fn/stufen/list-uebungen';
export { listUebungen as listUebungen } from './fn/stufen/list-uebungen';
export type { AssignLeiter$Params as AssignLeiter$Params } from './fn/stufen/assign-leiter';
export { assignLeiter as assignLeiter } from './fn/stufen/assign-leiter';
export type { RemoveLeiter$Params as RemoveLeiter$Params } from './fn/stufen/remove-leiter';
export { removeLeiter as removeLeiter } from './fn/stufen/remove-leiter';
export type { UpdateRoles$Params as UpdateRoles$Params } from './fn/admin/update-roles';
export { updateRoles as updateRoles } from './fn/admin/update-roles';
export type { Invite$Params as Invite$Params } from './fn/admin/invite';
export { invite as invite } from './fn/admin/invite';
export type { ListUsers$Params as ListUsers$Params } from './fn/admin/list-users';
export { listUsers as listUsers } from './fn/admin/list-users';
export type { GetMe$Params as GetMe$Params } from './fn/users/get-me';
export { getMe as getMe } from './fn/users/get-me';
