/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AssignLeiterRequest } from './models/assign-leiter-request';
export type { InviteRequest } from './models/invite-request';
export type { LeiterDto } from './models/leiter-dto';
export type { LocalTime } from './models/local-time';
export type { RoleUpdateRequest } from './models/role-update-request';
export type { StufeDetailDto } from './models/stufe-detail-dto';
export type { StufeOverviewDto } from './models/stufe-overview-dto';
export type { StufeRequest } from './models/stufe-request';
export type { UebungCreateRequest } from './models/uebung-create-request';
export type { UebungDto } from './models/uebung-dto';
export type { UebungStatusRequest } from './models/uebung-status-request';
export type { UserResponse } from './models/user-response';
