/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UebungDto } from '../../models/uebung-dto';
import { UebungStatusRequest } from '../../models/uebung-status-request';

export interface SetStatus$Params {
  id: number;
      body: UebungStatusRequest
}

export function setStatus(http: HttpClient, rootUrl: string, params: SetStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<UebungDto>> {
  const rb = new RequestBuilder(rootUrl, setStatus.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UebungDto>;
    })
  );
}

setStatus.PATH = '/uebungen/{id}/status';
