/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InviteRequest {
  email: string;
  roles?: Array<'ROLE_ADMIN' | 'ROLE_ABTEILUNGSLEITER' | 'ROLE_STUFENLEITER' | 'ROLE_LEITER'>;
}
