/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LeiterDto {
  displayRole?: string;
  email?: string;
  id?: number;
  pfadiName?: string;
  profilePhotoUrl?: string;
  sortOrder?: number;
}
