/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StufeRequest {
  description?: string;
  googleCalendarIframeUrl?: string;
  groupPhotoUrl?: string;
  name?: string;
  primaryColor?: string;
  slug?: string;
  tagline?: string;
}
