/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LeiterDto } from '../models/leiter-dto';
import { UebungDto } from '../models/uebung-dto';
export interface StufeDetailDto {
  description?: string;
  googleCalendarIframeUrl?: string;
  groupPhotoUrl?: string;
  id?: number;
  leitungsteam?: Array<LeiterDto>;
  name?: string;
  nextUebung?: UebungDto;
  primaryColor?: string;
  slug?: string;
  tagline?: string;
}
