/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StufeOverviewDto {
  groupPhotoUrl?: string;
  id?: number;
  name?: string;
  primaryColor?: string;
  slug?: string;
  tagline?: string;
}
