/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  email?: string;
  id?: number;
  pfadiName?: string;
  profilePhotoUrl?: string;
  roles?: Array<string>;
}
